---
- name: Instalación y configuración de aplicaciones en Ubuntu
  hosts: #### Especificar hostname #####
  become: yes

  tasks:
    - name: Instalar Visual Studio Code utilizando Snap
      snap:
        name: "code"
        classic: yes
        state: present

    - name: Instalar Docker utilizando Snap
      snap:
        name: "docker"
        state: present

    - name: Instalar paquetes base usando APT
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - default-jdk  # Instala el último JDK disponible
        - git
        - ansible
        - npm
        - php
        - wireshark
        - traceroute
        - gparted
        - remmina
        - meld
        - nmap
        - net-tools
        - dbeaver-ce
      ignore_errors: yes

    - name: Instalar Postman usando Snap
      snap:
        name: "postman"
        state: present

    - name: Instalar iCloud Notes usando Snap
      snap:
        name: "icloud-notes"
        state: present

    - name: Actualizar lista de paquetes e instalar actualizaciones
      apt:
        upgrade: dist
        update_cache: yes
        autoremove: yes
        autoclean: yes